@startuml Domain model

hide circle

namespace Shared <<Rectangle>> {
    class GroupId << ValueObject >> {
        -value: str
    }
    class DocumentTypeId << ValueObject >> {
        -value: str
    }
    class TenantId << ValueObject >> {
        -value: str
    }
}

namespace Groups <<Rectangle>> {
    class Group << Aggregate >> {
        -id: GroupId
        -t_id: TenantId
        -name: str
        -tags: set[Tag]
        -created_at: datetime
        -updated_at: datetime
        -document_types: list[DocumentTypeId]
        +update_info(name: str, tags: list[str] | None): None
        +delete(): None
        +add_document_type(dt_id: str): None
        +remove_document_type(dt_id: str): None
    }
    note left of Group::name
        max length: 100
    end note

    note left of Group::update_info
        Provided tags should override old ones fully
    end note

    Group *-- "0..25" DocumentTypeId
    Group *-- "1" GroupId
    Group *-- "1" TenantId
    Group *-- "0..5" Tag

    class Tag << Value Object >> {
        -value: str
    }
    note right of Tag::value
        max length: 72
    end note

    class GroupCreated << Event >> {
        +id: str
        +t_id: str
        +name: str
        +tags: list[str]
        +document_types: list[str]
    }

    class GroupInfoUpdated << Event >> {
        +id: str
        +t_id: str
        +name: str
        +tags: list[str]
    }

    class GroupDeleted << Event >> {
        +id: str
        +t_id: str
    }

    class DocumentTypeAdded << Event >> {
        +id: str
        +t_id: str
        +dt_id: str
    }

    class DocumentTypeRemoved << Event >> {
        +id: str
        +t_id: str
        +dt_id: str
    }

    class GroupRepository << Repository >> {
        +group_of_id(id: str, t_id: str): Group | None
        +groups_of_ids(ids: list[str], t_id: str): list[Group]
        +has_group_with_name(name: str, t_id: str): bool
        +save(group: Group): None
        +delete_all(groups: list[Group]): None
    }

    class GroupFactory << Factory >> {
        {static} +create(t_id: str, name: str, dt_ids: list[str], tags: list[str] | None): Group
    }

    class GroupService << Application >> {
        -group_repository: GroupRepository
        +create(t_id: str, name: str, dt_ids: list[str], tags: list[str] | None): Group
        +update_info(id: str, t_id: str, name: str, tags: list[str] | None): Group
        +delete(ids: list[str], t_id: str): list[Group]
        +add_document_type(id: str, t_id: str, dt_id: str): Group
        +remove_document_type(id: str, t_id: str, dt_id: str): Group
    }

    GroupService *-- "1" GroupRepository
    GroupService --> GroupFactory
    GroupService --> Group : uses
    GroupFactory --> Group : instantiates
    GroupRepository --> Group : retrieves/stores

    class QueryGroupRepository << Repository >> {
        +find_groups(): list[GroupInfo]
    }

    class QueryGroupService << Application >> {
        -group_repository: QueryGroupRepository
        +find_groups(): list[GroupInfo]
    }
    note left of QueryGroupService::find_groups
        Pagination
        Combined search by name and tags
        Ordering by name, created date (default)
    end note

    QueryGroupService *-- "1" QueryGroupRepository
}

namespace DocumentTypes <<Rectangle>> {
    class DocumentType << Aggregate >> {
        -id: EntityId
        -tenant_id: TenantId
    }

    DocumentType *-- "1" TenantId
    DocumentType *-- "1" DocumentTypeId

    class DocumentTypeFactory << Factory >> {
        {static} +create(id: str, t_id: str): DocumentType
    }

    class DocumentTypeRepository << Repository >> {
        +document_type_of_id(id: str, t_id: str): DocumentType | None
        +document_types_of_invalid_ids(ids: list[str], t_id: str): dict[str, bool]
        +save_new(document_type: DocumentType): None
        +save_all(document_types: list[DocumentType]): None
        +delete(document_type: DocumentType): None
    }

    class DocumentTypeService << Application >> {
        -document_type_repository: DocumentTypeRepository
        +obtain_all(): None
        +save_all(document_types_info: list[dict[str, str]]): list[DocumentType]
        +create(id: str, t_id: str): DocumentType
        +delete(id: str, t_id: str): list[DocumentTypes]
    }

    DocumentTypeService *-- "1" DocumentTypeRepository
    DocumentTypeService --> DocumentType : uses
    DocumentTypeFactory --> DocumentType : instantiates
    DocumentTypeRepository --> DocumentType : retrieves/stores
}
@enduml
